% Mechanistic Regulation Of Planarian Shape During Growth And Degrowth
% (c) Lobo Lab - lobo@umbc.edu

 function [averWallsX, averWallsY] = average2(input, p)
% (c) Lobo Lab - lobo@umbc.edu

  d3 = size(input, 3);

  % dimensions in cell walls
  averWallsX = zeros(p.numSimCellWallsX, p.numSimCellWallsY, d3);
  averWallsY = zeros(p.numSimCellWallsX, p.numSimCellWallsY, d3);
  
  averWallsX(1:p.numSimCellsX, 2:p.numSimCellsY, :) = ...
          (input(:, 2:p.numSimCellsY,   :)            ...
            +                                         ...
           input(:, 1:p.numSimCellsY-1, :))           ...
          / 2;
  
  averWallsY(2:p.numSimCellsX, 1:p.numSimCellsY, :) = ...
          (input(2:p.numSimCellsX,   :, :)            ...
            +                                         ...
           input(1:p.numSimCellsX-1, :, :))           ...
          / 2;

end
