% Mechanistic Regulation Of Planarian Shape During Growth And Degrowth
% (c) Lobo Lab - lobo@umbc.edu

 function [div] = divergence2(inputX, inputY, p)
% (c) Lobo Lab - lobo@umbc.edu

  d3 = size(inputX, 3);
  
  
  div = zeros(p.numSimCellsX, p.numSimCellsY, d3);
  
  
  div(2:p.numSimCellsX-1, 2:p.numSimCellsY-1, :) = ...
          (inputX(2:p.numSimCellsX-1, 3:p.numSimCellsY,   :)   ...
          	 -                                                  ...
           inputX(2:p.numSimCellsX-1, 2:p.numSimCellsY-1, :))  ...
          / p.dx                                               ...
             ...
          +  ...
             ...
          (inputY(3:p.numSimCellsX,   2:p.numSimCellsY-1, :)   ...
            -                                                  ...
           inputY(2:p.numSimCellsX-1, 2:p.numSimCellsY-1, :))  ...
          / p.dy;
               
end

