% Mechanistic Regulation Of Planarian Shape During Growth And Degrowth
% (c) Lobo Lab - lobo@umbc.edu

 function [gradWallsX, gradWallsY] = gradient2(input, p)
% (c) Lobo Lab - lobo@umbc.edu

  d3 = size(input, 3);

  % dimensions in cell walls
  gradWallsX = zeros(p.numSimCellWallsX, p.numSimCellWallsY, d3);
  gradWallsY = zeros(p.numSimCellWallsX, p.numSimCellWallsY, d3);
  
  gradWallsX(1:p.numSimCellsX, 2:p.numSimCellsY, :) = ...
          (input(:, 2:p.numSimCellsY,   :)            ...
            -                                         ...
           input(:, 1:p.numSimCellsY-1, :))           ...
          / p.dx;
  
  gradWallsY(2:p.numSimCellsX, 1:p.numSimCellsY, :) = ...
          (input(2:p.numSimCellsX,   :, :)            ...
            -                                         ...
           input(1:p.numSimCellsX-1, :, :))           ...
          / p.dy;

%   gradWallsX(2:p.numSimCellsX-1, 2:p.numSimCellsY, :) = ...
%     (input(2:p.numSimCellsX-1, 2:p.numSimCellsY, :) - input(2:p.numSimCellsX-1, 1:p.numSimCellsY-1, :))/p.dx + ...
%     (input(1:p.numSimCellsX-2, 2:p.numSimCellsY, :) - input(1:p.numSimCellsX-2, 1:p.numSimCellsY-1, :) + ...
%      input(3:p.numSimCellsX, 2:p.numSimCellsY, :) - input(3:p.numSimCellsX, 1:p.numSimCellsY-1, :))/(2*sqrt(2)*p.dx);
%   
%   gradWallsY(2:p.numSimCellsX, 2:p.numSimCellsY-1, :) = ...
%     (input(2:p.numSimCellsX, 2:p.numSimCellsY-1, :) - input(1:p.numSimCellsX-1, 2:p.numSimCellsY-1, :))/p.dx + ...
%     (input(2:p.numSimCellsX, 1:p.numSimCellsY-2, :) - input(1:p.numSimCellsX-1, 1:p.numSimCellsY-2, :) + ...
%      input(2:p.numSimCellsX, 3:p.numSimCellsY, :) - input(1:p.numSimCellsX-1, 3:p.numSimCellsY, :))/(2*sqrt(2)*p.dy);

end
